### ISSUE TITLE
Worldmap improvements

### ISSUE THREAD

**Issue by Tomash667** [Tomash667/carpg#27]
Map should be scaleable and scrollable. Player can scale with mouse wheel, move it around with right mouse button. Travel can be set to any point on map with left mouse button. With shift it will be added as waypoint (like in Arcanum).

Hovering location with mouse will show it name and other information. Some places have text written on map (like Dungemore Mountains).

Add window to search for location for name (shortcut F). Locations matching text should be highlighted + line from player to location.

Player can open map from location and it shows as overlay (like journal). There should be ability to open map and highlight location and route to it (for example: player opens journal and there is quest with text about some location, it is link, when players clicks on it, it will open worldmap and highlight that location).

Draw old path with decreased alpha value to show player from where he came.

**Comment by Leinnan** [comment]
> Add window to search for location for name (shortcut F). Locations matching text should be highlighted + line from player to location.
If you dont use any keyboard key for moving on map you can start searching by just start writing anything. IMO

**Comment by Tomash667** [comment]
J - journal
T - fast travel (devmode)
There may be more shortcuts later, so better press F.

**Comment by Leinnan** [comment]
So the best if player start typing letters will be:
-check is key isn't any shortcut
-if not start searching

**Comment by Tomash667** [comment]
@Leinnan I started using new site https://tree.taiga.io/project/tomash667-carpg/ , take a look :smile: 
You want to go to location starting with T, but after pressing T it will teleport to other location so how would you search for it?

**Comment by Leinnan** [comment]
You just still left F for searching- instead of one option left them both.

**Comment by Tomash667** [comment]
Moved to epic #72
