### ISSUE TITLE
CaRPG v0.12 crashes on main menu without Internet

### ISSUE THREAD

**Issue by codergreen** [Tomash667/carpg#402]
Tried CaRPG without Internet. It froze on the main menu for 10 seconds and crashed. Unable to move mouse or anything for 10 seconds. If it starts up with internet, it works fine. If I disconnect from the internet while on the main menu the menu still works. I'm guessing this isn't intended?

**Comment by Tomash667** [comment]
Thanks for reporting this. It shouldn't crash - I'll check this out.

**Comment by Tomash667** [comment]
I tested it and everything works fine for me, no freeze or crash.

Can you send crash thru crash reporter window when this happens or send some logs.

**Comment by Tomash667** [comment]
If this is still happening comment here and I will reopen this issue.
