### ISSUE TITLE
Inventory Carry Capacity Logic Error

### ISSUE THREAD

**Issue by Lemiczek** [Tomash667/carpg#406]
When you reach the exact carry limit the red text turns back to black but the overburdened status effect still applies.

for example:
```
Carry: 75/75 kg <-- black text but still overburdened
Carry: 75.1/75 kg <-- red text overburdened
```

**Comment by Tomash667** [comment]
Thanks, will be fixed in 0.14 which hopefully will be release soon.

Now overloads happens after exceeding carry capacity (75.1).
