### ISSUE TITLE
Items' rotation

### ISSUE THREAD

**Issue by lcs2** [Tomash667/carpg#41]
- In the inventory, items should rotate along their Y axis, around 25 degrees angled toward X axis.
- It should be triggered by hovering over the selected item.  Moving the cursor away should bring animation back to the starting position.

**Comment by Tomash667** [comment]
@lcs2 In normal inventory or in box that shows when hovering mouse over item? I think it will be better with the other option.
Some items don't have mesh so they can't be rotated.

**Comment by lcs2** [comment]
Then rotate only these which have it.
Equipment items, like armors and swords, should rotate in order to let player see its full design and admire the all astonishing details.
