### ISSUE TITLE
Rogue dash ability broken after Arena

### ISSUE THREAD

**Issue by Lemiczek** [Tomash667/carpg#412]
When you get defeated in Arena (Duel or Fight at Arena), the dash ability will not work in certain adjacent positions (down and right, left and top, etc...). This issue persists until the player leaves the town or saves and loads the game.

Steps to reproduce:
1) Go to Arena
2) Die
3) Your dash ability now doesn't work in 2 directions regardless of the position your character is facing.

**Comment by Tomash667** [comment]
Fixed in 0.14.
