### ISSUE TITLE
Multiplayer health bar above players/NPCs does not update correctly

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#413]
I have noticed a bug in multiplayer, when playing as client,
health bar shown above characters sometimes does not matches to the real health value.
This happens after a player or NPC gets knocked out and then wakes up.
They typically have 1 HP, while the health bar says they are fully healed.
Upon first health change, the label above player/NPC refreshes and shows adequate amount of health.

This bug has been reproduced successfully.
It is tied to clients, server sees everything normal.

Seems like a synchronization problem, as server does not update its clients properly.

Steps to reproduce:
1) Play in multiplayer as a client
2) Observe your teammate got knocked out
3) When he stands up again, his health bar say it he is fully healed, but really is not

**Comment by Tomash667** [comment]
Fixed in 0.14.
