### ISSUE TITLE
Multiplayer map synchronization weirdness

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#414]
I encountered a bug in multiplayer where all of sudden, map did not matched to that of other players.
It was quite funny bug. I think it is hardly reproducible, it was probably just caused by packet loss.

#### Additional context:
For me:
![scree1](https://user-images.githubusercontent.com/62666666/77691833-df9b3800-6fa5-11ea-9fee-c5739a5b6fcf.png)
For bystanders:
![scree2](https://user-images.githubusercontent.com/62666666/77691842-e164fb80-6fa5-11ea-96e1-4697e2a58873.png)

**Comment by Tomash667** [comment]
Fixed in 0.14. That was bug in library, they fixed it but in forever todo branch.
