### ISSUE TITLE
Weird character placement and downwarp using a wand and seat

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#415]
This bug happens while repeatedly pressing draw weapon (while wand is equipped),
while sitting on stool/bench and then quickly pressing mouse buttons.
This resulted in downwarp or levitation.
It has been replicated several times by @Lemiczek and myself.

Steps to reproduce:
1) Find a free stool/bench and sit on it.
2) Draw/hide some wand several times.
3) While doing step three repeatedly press left and right mouse buttons.
4) Hide your wand and while animation is in progress, press some mouse buttons.
5) You may observe a downwarp, levitation or speed launch.

It may be it bit harder to reproduce without proper rythm or instructions.
This is probably wand specific, other weapons did not have this effect.
It worked in exteriors and interiors alike.

Here is some photographic documentation:
![scree](https://user-images.githubusercontent.com/62666666/77706683-5eeb3480-6fc3-11ea-8b42-86009cd2bb69.png)
![scree2](https://user-images.githubusercontent.com/62666666/77706686-601c6180-6fc3-11ea-92da-34550dffb50f.png)
![scree3](https://user-images.githubusercontent.com/62666666/77706691-61e62500-6fc3-11ea-8242-f4de74aa2b34.png)

**Comment by Lemiczek** [comment]
I have provided some video footage for further documentation of this bug:
https://www.youtube.com/watch?v=x24ErzvYTUA

**Comment by Tomash667** [comment]
Fixed in 0.14.
