### ISSUE TITLE
Stuck on small crate on Dash/Bull's charge ability

### ISSUE THREAD

**Issue by Lemiczek** [Tomash667/carpg#416]
If a rogue/warrior use their abilities on a specific small crate the players get stuck until they use their ability again.
![Stuck](https://user-images.githubusercontent.com/38136466/77709387-29e2e000-6fcb-11ea-98df-5b907b5e53c2.png)
![Stuck2](https://user-images.githubusercontent.com/38136466/77709400-2e0efd80-6fcb-11ea-8ddd-73dfa3876b5f.png)

**Comment by BottledByte** [comment]
I can confirm that. And the same issue applies to benches.

**Comment by Tomash667** [comment]
Looks like this can be used to move thru (or stuck) inside any low height object.

**Comment by Tomash667** [comment]
Fixed in 0.14.
