### ISSUE TITLE
Bleeding edge builds prevented by lack of data files availability

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#419]
I downloaded the game's source and compiled it with success. I copied the data files from v0.13 next to the created binaries, but resource manager told me that it cannot locate "alchemy.mp3".
After I faked it's presence, it said that it cannot locate "journal_bts1.png"... and so on.
All the files were required by recent content additions. And README.md states that data files should be copied from the latest release when compiling from source. 

Some people could desire to stay on the bleeding-edge. (development branch)
This prevents them from doing so.
Availability of recent data files is required.

**I have three ideas on how to solve this:**
1) Most simple way is to upload them *somewhere* and require from user to manually download them. I consider this as quick and ugly solution, but passing in short term.
2) More advanced solution would be using a git/github by creating a new separate repository for them. It is possible to make it a submodule and make it fetchable along with the source or independently of it. Additional advantage is that it could even provide versioning for the data files.
3) Add the data files into source repo. But since git submodules are used anyway and you have to type that aditional line into console (or download the other repo manually without git), I do not think that it would produce that much comfort and the main repo could get a bit messy.

I am open for discussion, but bleeding edge builds and testing should be possible.

**Comment by Tomash667** [comment]
In my opinion second option is best for now. I commited changes to dev. If everything works I will close this issue.

**Comment by BottledByte** [comment]
Data files submodule works as expected. Bleeding edge built was successful and new assets can be observed in game.
Closing this issue.
