### ISSUE TITLE
Magic crystal does not have mana restoring effect

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#420]
Game version: 0.13
When low on mana and consuming a magic crystal nothing happens, while its description states that 150 mana should be restored. Either the mana restoring effect should happen upon consumption or its descriptions should be changed.
Personally, I do not think that a crystal should be consumable direcly (it is essentially a fancy rock) and with recent addition of alchemy, it should be used as ingredient only.

**Comment by Tomash667** [comment]
Fixed in 0.14.

Instead of restoring 150 mana it was set to increase mana by 150 for 0 seconds.

As of eating crystal: #422 If you have any more ideas add them there :)
