### ISSUE TITLE
Perk/feat selection during character creation behaves incorrectly

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#421]
Custom build, latest commit: 86828c02b5a026df7430369558bfe5d5ffa63315

This bug makes selecting perks/feats a bit annoying due to frequent pop-up messages which say that perk was deselected because its requirements were not met and actually deselecting mentioned trait. It happens even when no requirements are really there (Or maybe they are not obvious, but I do not think so).
This is recent build specific only, I was not able to reproduce on release 0.13. I estimate that recent perk de-hardcoding causes this and it seems that it is mainly associated with perks that have *history* flag, but other perks shows this behaviour sometimes when feat point gaining perks are selected and additional benefitial perks gets removed (so no feat point "lack" occurs). When two non-*history* traits are selected and one of them is then deselected, it works normally.

Steps to reproduce:
1) Start a new character, select a class
2) Assign perk Alchemist apprentice/Student of traveling merchant and some other perk (for example wealthy or sluggish), in any order
3) Change your mind and deselect the other perk
4) Observe a message saying "requirements not met, removing trait <name>"
5) Both traits get deselected and there is no correlation between them apart from that pop-up message

![scree](https://user-images.githubusercontent.com/62666666/77825865-4d617400-710c-11ea-8071-3ccc3c43e6e8.jpg)

**Comment by Tomash667** [comment]
Thanks, fixed.
