### ISSUE TITLE
Journal cycling while adding a note during world map

### ISSUE THREAD

**Issue by Lemiczek** [Tomash667/carpg#423]
When you are on the world map, open the journal and add a note. When you press the 123 or !@# keys (US keyboard) it will open the Quests/Rumors/Notes sections depending on which number you've pressed.

I believe that a focused text box should lock any other key binds.

**Steps to reproduce:**
1. Go to the world map
2. Open journal (default key J)
3. Go to notes
4. Click Add Note
5. press 1, 2 or 3 (Numpad doesn't trigger this behavior)

**Comment by Tomash667** [comment]
Fixed in 0.14.
