### ISSUE TITLE
Console causing game crash when extremely long integer is supplied to a command

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#425]
Thanks @Lemiczek for first noticing this.

While typing into developer console a command which accepts number, when numerical string reaches certain length and the command gets executed, it results in program's crash.
When I build the game with debug configuration, I received an error from Visual C++ Runtime that debug assertion failed and it stated that source of that failed assert is following:

![scree](https://user-images.githubusercontent.com/62666666/77847209-8a387400-71bb-11ea-8612-b092b1467244.png)

It is obviously not a part of game or its engine. I tried to track this issue, but I do not have debugging toolset. I tracked it into Tokenizer in carpglib, only to loose it there.
Based on my observation, it is not caused by Tokenizer's AssertXXX(), which, as I assume, should prevent this thing to go so deep into the Visual C++ Runtime.

**Comment by Lemiczek** [comment]
The extremely long integer is 4294967296 (2^32) or above. After this number, the game crashes instead of setting gold back to 0 as it does after 2147483647 (2^31 -1).

**Comment by Tomash667** [comment]
Fixed in 0.14.
