### ISSUE TITLE
Consumable items can be consumed without effect during knockout animation

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#426]
Game version: 0.13

While being knocked out and falling onto the ground, items consumed during that animation disappear / get consumed without any effect.
This bug can be observed easily. Get knocked out or drunk and while falling onto the ground, try to consume any consumables from your inventory. They will disappear, but nothing else happens.
Also, while lying on the ground, when you try to consume for example healing potion, its mesh will appear in character's hand. Other consumables then cannot be used and when the character is going back up again, the item disappears from character's hand and nothing else happens.

Side note: It is possible to interact with items in inventory while on ground (like de/equipping armor and weapons), which I think should not be possible, but be able to browse character's inventory is okay.

**Comment by Tomash667** [comment]
Fixed in 0.14. Now you can't use any item or try to drop items or gold when on ground.
