### ISSUE TITLE
MP Client looses collider (partial ghostification) and has broken animations from other's perspective after getting drunked

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#427]
Custom build, last commit: ccf35716f00065f686494d5121ea63ce2e266b5f
***I was not able to replicate this in version 0.13.***

@Lemiczek helped with this

Lots of weird behaviour happens when drinking a passing away due to alchohol and standing back up in MP as Client.

Character looses its collider from Unit's perspective, while character is still affected by other Unit physics on his side.
(Client can not pass through other players/NPCs/monsters, while they can walk through the character freely).
Character is unable to shoot arrows, damage others in any way or cast spells on other Units.
The animation can be seen on client side and respective player statistics changed (stamina, mana), but it has no effect (arrow is not shot, heal ability does not create sparks).
Other units can damage the client character freely.

Character animation / visual state seen at client does not matches to that observed at server. Items such as Spirit, ladle or arrow remained in character's hand.
When server saved and reload the game, client was able to observe the state in which server saw it at save time.
All these things can happen to client only.

**Steps to reproduce:**
1) Play in MP as a client
2) Get some amount of Spirit or other alchohol
3) Drink until passing away
4) Stand back up
5) Observe above-mentioned behaviour

This bug allowed us to take following screenshots:
Siameese twins and Laddle shot
![unknown](https://user-images.githubusercontent.com/62666666/77871111-67ea3900-7243-11ea-9b3c-0c952eaccc8e.png)

Spirit Shot
![unknown1](https://user-images.githubusercontent.com/62666666/77871113-691b6600-7243-11ea-80c6-7eb310c5e775.png)

Spirit-enhanced club
![unknown2](https://user-images.githubusercontent.com/62666666/77871116-6a4c9300-7243-11ea-9048-47a9f44965cf.png)

**Comment by Tomash667** [comment]
Fixed, thanks!

If you want unit to fall on ground you can use "fall" command, it will be a little faster than drinking spirit :)
