### ISSUE TITLE
MP Client character selection impossible when perk with history flag is selected 

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#428]
Custom build, last commit: ccf35716f00065f686494d5121ea63ce2e266b5f

When selecting character as a client in lobby, if the player chooses a trait with history flag (Alchemist apprentice / Student of travelling merchant) and continues with character creation, character does not get created.
Other perks do not seem to cause this behaviour.

Thanks @Lemiczek for help with testing.

**Comment by Tomash667** [comment]
Fixed, thanks!
