### ISSUE TITLE
New items system

### ISSUE THREAD

**Issue by Tomash667** [Tomash667/carpg#43]

**Comment by lcs2** [comment]
"CONSUMABLE"
while connecting words with "- ABLE" postfix, you delete the last letter if they end with "e"

**Comment by lcs2** [comment]
i would consider adding BELT item, adding stats but also ability to stack potions and use them with hotkeys. Some extra AURA slot would be an interesting idea, but not necessary at this point

**Comment by Tomash667** [comment]
Moved to #71
