### ISSUE TITLE
Crash on crafting in Alchemy

### ISSUE THREAD

**Issue by Lemiczek** [Tomash667/carpg#430]
This issue can be replicated by using more than one magic crystal in order to craft the Mana potion. There is a chance that the Mana Potion will lose its focused status, but will still allow you to press the craft button resulting in a crash upon clicking the craft button.

**Comment by Tomash667** [comment]
Fixed by @BottledByte in 0.15 (or in 0.14 patch, depending on what will be first).

**Comment by Tomash667** [comment]
Can still happen in MP for client, need to investigate 👀
