### ISSUE TITLE
numeric overflow when crafting in alchemy

### ISSUE THREAD

**Issue by Lemiczek** [Tomash667/carpg#435]
When a person has a singular magic stone or herb in inventory and tries to craft a small mana/health potion, the modal window to create multiple potions pops up. If a person then scrolls to create more potions the value -2147483648 (signed 2^31) pops up. the pop up then shows that -2147483648 potions were created but in reality, only 1 item was created.

**Steps to reproduce:**
1. Have alchemy skill
2. Get 1 mana crystal or 1 herb
3. Select a potion to create
4. scroll with the mouse wheel
![bug](https://user-images.githubusercontent.com/38136466/78256992-92fdb280-74f9-11ea-9286-91164b309929.png)

**Comment by Tomash667** [comment]
Fixed in 0.15.

Extra changes:
+ when player have ingredients for only 1 potion or when holding Control - create 1 potion without confirming
+ when holding Shift - create max potions
