### ISSUE TITLE
Proposal: Recipe learning

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#437]
Currently (v0.14), implementation of recipe learning is very simple. It just looks at list of all available recipes and if player has enough skill to use certain recipe, recipe will appear in crafting screen.

I propose a change where instead of showing recipe when *player skill >= required skill*, recipes could be *learned* or *discovered*. It could be done either by auto-learning (such as it is now; by reaching skill level) or by some other condition/event (learned from NPC, given as quest reward?...).

I think that making recipes learnable independent on skill could result in more content addition possibilites.

Edit:
List of steps required to implement this:
- [x] Make it possible to learn a recipe independently of skill in single-player
- [x] Make recipe learning work in multi-player
- [x] Create items that can teach a recipe (recipe books?)
- [ ] Apply the new mechanic in game (recipes can be found/sold by traders, autolearning)

**Comment by Tomash667** [comment]
👍

I had something similar planned but can't find it right now (it was inside some Epic issue).

Except what you written there can be "recipe" item that are single use item - after reading player will learn recipe (can have skill requirement too).
