### ISSUE TITLE
Dash ability ignores green transfer collider

### ISSUE THREAD

**Issue by Lemiczek** [Tomash667/carpg#438]
When a player dashes into the green transfer zone, he will remain in that zone without being transported. This means that a player can dash in and out of the green zone as a neat party trick. moving in the green zone results in normal expected behavior.
![ohno](https://user-images.githubusercontent.com/38136466/78414910-d1d95880-761e-11ea-9856-f146127657a6.png)

**Comment by Lemiczek** [comment]
I believe this will no longer be an issue because of #417.

**Comment by Tomash667** [comment]
@Lemiczek i won't call this bug, you can walk into any region with shift without transporting.

**Comment by Lemiczek** [comment]
Oh, I didn't realize that! Closing the issue in that case.
